project '48Stars.xcodeproj'

platform :ios, '18.0'

target '48Stars' do
  use_frameworks!
  pod 'GoogleMaps'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '18.0'
    end
  end
end
warn_for_unused_master_specs_repo => false